"use client";
import { useCallback,useEffect,useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { BRANCHES,formatPrice,type Extra } from "@/lib/catalog";
import { ConfirmAction } from "@/components/confirm-action";
import { canTransition } from "@/lib/shop-rules";
const statuses:Record<string,string>={new:"Новый",confirmed:"Подтверждён",assembling:"Собираем",ready:"Готов",completed:"Выдан",cancelled:"Отменён"};
const payments:Record<string,string>={not_required:"Без онлайн-оплаты",pending:"Ожидает оплаты",paid:"Оплачен",refund_pending:"Возврат обрабатывается",refunded:"Возвращён"};
type Order={id:string;version:number;orderNumber:string;customerName:string;phone:string;recipientName:string;recipientPhone:string;fulfillment:string;branchId:string;address:string;deliveryDate:string;deliveryTime:string;deliveryDetails:string;comment:string;subtotal:number;deliveryPrice:number;bonusSpent:number;total:number;status:string;paymentStatus:string;robokassaInvoiceId:string|null;items:{id:number;productName:string;variantName:string;quantity:number;price:number;extrasJson:string}[]};
export function AdminOrders({customerId}:{customerId?:string}) {
  const [rows,setRows]=useState<Order[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[loading,setLoading]=useState(false),[selected,setSelected]=useState<Order|null>(null),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{
    setLoading(true);try {const u=new URLSearchParams({page:String(page),q:query,status:status==="all"?"":status,customer:customerId||""});
      const r=await fetch("/api/orders?"+u),d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.orders);setMore(d.hasMore);setSelected(current=>current?d.orders.find((o:Order)=>o.id===current.id)||null:null);
    }catch(e){toast.error(e instanceof Error?e.message:"Не удалось загрузить заказы");}finally{setLoading(false);}
  },[page,query,status,customerId]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer);},[load]);
  async function update(order:Order,values:Record<string,unknown>) {
    setBusy(true);try {const r=await fetch("/api/orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:order.id,version:order.version,...values})}),d=await r.json();if(!r.ok)throw new Error(d.error);toast.success("Заказ обновлён");await load();}catch(e){toast.error(e instanceof Error?e.message:"Не удалось сохранить");}finally{setBusy(false);}
  }
  async function refund(order:Order,action:string) {
    setBusy(true);try {const r=await fetch("/api/payment/refund",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:order.id,action})}),d=await r.json();if(!r.ok)throw new Error(d.error);toast.success(d.status==="finished"?"Возврат подтверждён":"Статус возврата: "+d.status);await load();}catch(e){toast.error(e instanceof Error?e.message:"Не удалось выполнить возврат");}finally{setBusy(false);}
  }
  let details:Record<string,unknown>={};try{details=JSON.parse(selected?.deliveryDetails||"{}");}catch{}
  return <div><div className="admin-section-head"><h2>Заказы</h2><Button variant="outline" onClick={()=>void load()}>Обновить</Button></div><div className="admin-filter-row"><input aria-label="Поиск заказов" placeholder="Номер заказа или телефон" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/><Select value={status} onValueChange={v=>{setStatus(v);setPage(0);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Все статусы</SelectItem>{Object.entries(statuses).map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select></div>
    {loading?<p role="status">Загружаем…</p>:!rows.length?<p>Заказов не найдено.</p>:<div className="order-list">{rows.map(o=><button key={o.id} className="order-card order-open" onClick={()=>setSelected(o)}><div className="order-card-head"><strong>{o.orderNumber}</strong><strong>{formatPrice(o.total)}</strong></div><h3>{o.customerName}</h3><p>{o.phone} · {o.deliveryDate} {o.deliveryTime}</p><p>{statuses[o.status]} · {payments[o.paymentStatus]}</p><span>Открыть заказ →</span></button>)}</div>}
    <div className="map-actions"><Button variant="outline" disabled={!page||loading} onClick={()=>setPage(page-1)}>Назад</Button><span>Страница {page+1}</span><Button variant="outline" disabled={!more||loading} onClick={()=>setPage(page+1)}>Далее</Button></div>
    <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="order-detail-dialog"><DialogHeader><DialogTitle>{selected?.orderNumber}</DialogTitle><DialogDescription>Состав, контакты, получение и оплата.</DialogDescription></DialogHeader>{selected && <div className="order-detail"><>{details.paymentTest===true&&<p className="test-payment-note">Тестовый заказ. Деньги не списывались; реальная доставка и возврат не требуются.</p>}</><h3>Покупатель</h3><p>{selected.customerName} · <a href={"tel:"+selected.phone}>{selected.phone}</a></p>{selected.recipientName && <><h3>Получатель</h3><p>{selected.recipientName} · <a href={"tel:"+selected.recipientPhone}>{selected.recipientPhone}</a></p></>}<h3>{selected.fulfillment==="pickup"?"Самовывоз":"Доставка"}</h3><p>{selected.deliveryDate} · {selected.deliveryTime} (Екатеринбург)</p><p>{selected.fulfillment==="pickup"?BRANCHES.find(b=>b.id===selected.branchId)?.address:selected.address}</p>{(["apartment","entrance","floor","intercom"] as const).map((k,i)=>details[k]?<p key={k}>{["Квартира / офис","Подъезд","Этаж","Домофон"][i]}: {String(details[k])}</p>:null)}
      <h3>Состав заказа</h3>{selected.items.map(i=><article key={i.id} className="order-item-detail"><strong>{i.productName} · {i.variantName} × {i.quantity}</strong><span>{formatPrice(i.price*i.quantity)}</span><small>{extrasText(i.extrasJson)}</small></article>)}<p>Товары: {formatPrice(selected.subtotal)} · Доставка: {formatPrice(selected.deliveryPrice)} · Бонусы: −{formatPrice(selected.bonusSpent)}</p><h3>Итого: {formatPrice(selected.total)}</h3>{selected.status==="completed" && selected.robokassaInvoiceId && <Button variant="outline" onClick={async()=>{try{await fetch("/api/admin/fiscal",{method:"POST"});const r=await fetch("/api/admin/fiscal?order="+selected.id),d=await r.json();toast.info(d.receipt?"Итоговый чек: "+({new:"в очереди",pending:"ожидает подтверждения",done:"зарегистрирован",error:"ошибка, проверьте кабинет Робокассы"}[d.receipt.status as "new"]||d.receipt.status):"Итоговый чек ещё не создан или не требуется для этого способа расчёта");}catch{toast.error("Не удалось проверить чек");}}}>Проверить итоговый чек</Button>}{selected.comment&&<p className="order-comment">{selected.comment}</p>}<p>Оплата: <strong>{payments[selected.paymentStatus]}</strong></p>
      <label><span>Статус заказа</span><Select disabled={busy} value={selected.status} onValueChange={status=>void update(selected,{status})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(statuses).filter(([v])=>canTransition(selected.status,v)).map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select></label>
      {!selected.robokassaInvoiceId && selected.paymentStatus==="not_required" && <Button disabled={busy} variant="outline" onClick={()=>void update(selected,{paymentStatus:"paid"})}>Отметить оплату при получении</Button>}
      {selected.robokassaInvoiceId && selected.paymentStatus==="paid" && <ConfirmAction disabled={busy} label="Вернуть всю сумму через Робокассу" description={"Будет запрошен возврат "+formatPrice(selected.total)+". Повторный запрос заблокирован до проверки результата."} onConfirm={()=>void refund(selected,"create")}/>}
      {selected.paymentStatus==="refund_pending" && <Button disabled={busy} variant="outline" onClick={()=>void refund(selected,"check")}>Проверить возврат</Button>}
    </div>}</DialogContent></Dialog>
  </div>;
}
function extrasText(raw:string) {try {const extras=JSON.parse(raw) as Extra[];const counts=new Map<string,{name:string;count:number}>();for(const e of extras){const old=counts.get(e.id);counts.set(e.id,{name:e.name,count:(old?.count||0)+1});}return [...counts.values()].map(e=>e.name+" × "+e.count).join("; ");}catch{return "";}}
