"use client";
import { useEffect,useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Dialog,DialogContent,DialogTitle } from "@/components/ui/dialog";
import { DEFAULT_SETTINGS, type Category,type Extra } from "@/lib/catalog";
import { ConfirmAction } from "@/components/confirm-action";
import { AdminOrders } from "@/components/admin-orders";
type Mutate=(p:Record<string,string|number|boolean|object|null|undefined>,message?:string)=>Promise<void>;
export function CategoryEditor({rows,mutate}:{rows:Category[];mutate:Mutate}) {
  return <div><h2>Разделы каталога</h2><p>Переименование сохранит товары в разделе. Скрытие уберёт раздел и его товары с витрины.</p><form className="admin-inline-create" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;void mutate({entity:"category",action:"create",name:new FormData(form).get("name") as string},"Раздел добавлен");}}><input name="name" required maxLength={100} placeholder="Новый раздел"/><Button>Добавить</Button></form>{rows.map(c=><form key={c.id+":"+c.name} className="inline-editor" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate({entity:"category",id:c.id,name:String(f.get("name")),sortOrder:Number(f.get("sortOrder")),visible:c.visible});}}><label>Название<input name="name" defaultValue={c.name} required/></label><label>Порядок<input type="number" name="sortOrder" defaultValue={c.sortOrder}/></label><label>Показывать<Switch checked={c.visible} onCheckedChange={visible=>void mutate({entity:"category",...c,visible})}/></label><Button>Сохранить</Button><ConfirmAction label="Удалить раздел" description="Удалить можно только раздел без товаров." onConfirm={()=>void mutate({entity:"category",action:"delete",id:c.id})}/></form>)}</div>;
}
export function VacancyEditor({rows,mutate}:{rows:{id:number;title:string;description:string;active:boolean}[];mutate:Mutate}) {
  return <div className="vacancy-admin"><h2>Вакансии</h2>{[{id:0,title:"",description:"",active:true},...rows].map(v=><form key={v.id+v.title+v.description} className="vacancy-editor" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate({entity:"vacancy",id:v.id,action:v.id?"update":"create",title:String(f.get("title")),description:String(f.get("description")),active:f.get("active")==="on"});}}><label>Название<input name="title" defaultValue={v.title} required placeholder="Новая вакансия"/></label><label>Условия и требования<textarea name="description" rows={5} maxLength={10000} defaultValue={v.description}/></label><label className="check-row"><input type="checkbox" name="active" defaultChecked={v.active}/>Опубликована</label><div className="map-actions"><Button>{v.id?"Сохранить изменения":"Добавить вакансию"}</Button>{!!v.id&&<ConfirmAction label="Удалить вакансию" description="Вакансия будет удалена с сайта." onConfirm={()=>void mutate({entity:"vacancy",action:"delete",id:v.id})}/>}</div></form>)}</div>;
}
export function ExtrasEditor({extras,onChange}:{extras:Extra[];onChange:(v:Extra[])=>void}) {
  async function upload(index:number,file:File|undefined){if(!file)return;try{const form=new FormData();form.append("file",file);const r=await fetch("/api/uploads",{method:"POST",body:form}),d=await r.json();if(!r.ok)throw new Error(d.error);onChange(extras.map((e,i)=>i===index?{...e,image:d.url}:e));}catch(e){toast.error(e instanceof Error?e.message:"Не удалось загрузить");}}
  return <div className="extras-editor"><h3>Сопутствующие товары</h3><p>Одиночные цветы теперь редактируются в каталоге: включите «Одиночный цветок» в карточке товара. Они автоматически появятся в дополнениях к букету.</p>{extras.map((e,i)=>e.kind==="flower"?null:<fieldset key={e.id} className="extra-admin"><legend>{e.name||"Новое дополнение"}</legend><label>Название<input required value={e.name} onChange={v=>onChange(extras.map((x,j)=>i===j?{...x,name:v.target.value}:x))}/></label><label>Цена за штуку<input type="number" min={0} required value={e.price} onChange={v=>onChange(extras.map((x,j)=>i===j?{...x,price:Number(v.target.value)}:x))}/></label><label>Описание<input value={e.description} onChange={v=>onChange(extras.map((x,j)=>i===j?{...x,description:v.target.value}:x))}/></label><label>В наличии<Switch checked={e.available!==false} onCheckedChange={available=>onChange(extras.map((x,j)=>i===j?{...x,available}:x))}/></label><label>Фотография<input type="file" accept="image/jpeg,image/png,image/webp" onChange={v=>void upload(i,v.target.files?.[0])}/></label><ConfirmAction label="Удалить дополнение" description="Изменение применится после сохранения настроек." onConfirm={()=>onChange(extras.filter((_,j)=>j!==i))}/></fieldset>)}<Button type="button" variant="outline" onClick={()=>onChange([...extras,{id:crypto.randomUUID(),name:"",description:"",price:0,available:true,kind:"accessory"}])}>Добавить сопутствующий товар</Button><p>Изменения применятся после нажатия «Сохранить настройки».</p></div>;
}
export function TelegramSettings() {
  const [rows,setRows]=useState<{chat_id:string;name:string}[]>([]),[ready,setReady]=useState(false),[link,setLink]=useState("");
  const [bot,setBot]=useState(""),[webhook,setWebhook]=useState<{connected:boolean;lastError?:string|null}|null>(null);
  async function load(){try{const r=await fetch("/api/telegram"),d=await r.json();if(!r.ok)throw new Error();setReady(d.ready);setRows(d.subscribers||[]);setBot(d.username||"");setWebhook(d.webhook||null);}catch{toast.error("Не удалось проверить подключение Telegram");}}
  useEffect(()=>{void load();},[]);
  async function action(values:object){try{const r=await fetch("/api/telegram",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(values)}),d=await r.json();if(!r.ok)throw new Error(d.error);if(d.url)setLink(d.url);await load();}catch(e){toast.error(e instanceof Error?e.message:"Не удалось подключить");}}
  return <section className="integration-card"><h2>Telegram: вход и уведомления</h2>{bot&&<p>Бот: <a href={"https://t.me/"+bot} target="_blank" rel="noopener">@{bot}</a></p>}{webhook&&<p>Связь с сайтом: {webhook.connected?"подключена":"требует подключения"}{webhook.lastError?" · "+webhook.lastError:""}</p>}{ready&&<Button type="button" variant="outline" onClick={()=>void action({action:"setup"})}>Обновить связь с сайтом</Button>}<p>{ready?"Токен настроен. Каждый сотрудник должен открыть личную ссылку и нажать Start.":"Ожидает токен бота и адрес опубликованного сайта."}</p><Button type="button" disabled={!ready} onClick={()=>void action({})}>Создать ссылку подключения сотрудника</Button>{link&&<p><a href={link} target="_blank" rel="noopener">Открыть Telegram</a><br/><input readOnly value={link} aria-label="Одноразовая ссылка"/><small>Действует 10 минут и только для одного подключения. Передавайте доверенному сотруднику.</small></p>}{rows.map(r=><p key={r.chat_id}>{r.name} <Button variant="outline" onClick={()=>void action({action:"remove",chatId:r.chat_id})}>Отключить</Button></p>)}<Button variant="outline" disabled={!ready} onClick={()=>void action({action:"retry"})}>Повторить неотправленные уведомления</Button></section>;
}
export function CustomersEditor({mutate}:{mutate:Mutate}) {
  const [rows,setRows]=useState<{id:string;name:string;phone:string;bonusBalance:number}[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[q,setQ]=useState(""),[selected,setSelected]=useState<string|null>(null);
  async function load(){const r=await fetch("/api/admin/customers?"+new URLSearchParams({page:String(page),q})),d=await r.json();if(r.ok){setRows(d.customers);setMore(d.hasMore);}else toast.error(d.error||"Не удалось загрузить клиентов");}
  useEffect(()=>{const timer=setTimeout(()=>void load().catch(()=>toast.error("Ошибка сети")),250);return()=>clearTimeout(timer);},[page,q]);
  return <div><h2>Покупатели и бонусы</h2><input className="admin-search-input" value={q} onChange={e=>{setQ(e.target.value);setPage(0);}} placeholder="Имя или телефон"/>{rows.map(c=><form className="inline-editor" key={c.id+":"+c.bonusBalance} onSubmit={e=>{e.preventDefault();const balance=Number(new FormData(e.currentTarget).get("balance"));void mutate({entity:"customer",id:c.id,bonusBalance:balance}).then(load);}}><div><strong>{c.name}</strong><p>{c.phone}</p></div><label>Баланс бонусов<input name="balance" type="number" min={0} defaultValue={Math.max(0,c.bonusBalance)}/></label><Button>Сохранить баланс</Button><Button type="button" variant="outline" onClick={()=>setSelected(c.id)}>История заказов</Button></form>)}<div className="map-actions"><Button variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>Назад</Button><span>Страница {page+1}</span><Button variant="outline" disabled={!more} onClick={()=>setPage(page+1)}>Далее</Button></div><Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="customer-history-dialog"><DialogTitle>История покупателя</DialogTitle>{selected&&<AdminOrders customerId={selected}/>}</DialogContent></Dialog></div>;
}
